# Generated by Django 5.1.4 on 2024-12-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategori_adı", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Müşteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("soyad", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("şifre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sipariş",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sipariş_tarihi", models.DateField()),
                (
                    "müşteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.müşteri"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ürün",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ürün_adı", models.CharField(max_length=255)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.kategori"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiparişÜrünleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.IntegerField()),
                (
                    "sipariş",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.sipariş"
                    ),
                ),
                (
                    "ürün",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ürün"
                    ),
                ),
            ],
        ),
    ]
